language: node_js
node_js:
  - "node"
before_install:
  - npm i -g makeshift && makeshift -s @bcoe -r https://npmo-demo-registry.npmjs.com
deploy:
  provider: npm
  email: ben@npmjs.com
  api_key: $NPM_TOKEN
  on:
    tags: true
